# Generated by Django 3.2.16 on 2023-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_card_serial', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
