# Generated by Django 3.2.16 on 2023-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='payment_card_serial',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
