version: "3.4"

services:
  nfclp:
    image: nfclp 
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn --reload nfclp.asgi:application --host 0.0.0.0 --port 8000
    env_file:
      - .env
    working_dir: /app/nfclp
    volumes:
      - ..:/app
  
  db:
    image: library/postgres:15-alpine
    restart: unless-stopped
    volumes:
      - nfclp-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nfclp
      - POSTGRES_PASSWORD=nfclp

volumes:
  nfclp-db:
    driver: local